all:
  children:
    staging:
      hosts:
        staging.assets.app:
          ansible_host: staging.assets.app
          env: staging
    production:
      hosts:
        assets.app:
          ansible_host: assets.app
          env: production
